### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by JohnScottMcNerney** [AlexDisler/cordova-plugin-inapppurchase#129]
### Your code / steps to reproduce
Difficult to reproduce, but basically:
(1) From home, go to my "store" screen which gets/displays consumable purchases. This works fine and has been stable for a while.
(2) Exit from "store" screen, back to home screen.
(3) Several seconds later, crash... (reproduction is very hard)

Maybe the IabHelper is trying to use an object that the V8 Garbage Collection removed (created in (1) but cleaned in (2) ).

Maybe add a check for a "null object" before calling the crashing routine?

### Console output
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
	at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:858)
	at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557)
	at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
	at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
	at java.lang.Thread.run(Thread.java:818)

### Type of product you are working with consumable/non-consumable/subscription
Consumable

### Version of cordova
Cordova 6.4.0

### Version of iOS/Android
Android 6.0

**Comment by palbaladejo** [comment]
Same here. Firebase report:

Exception java.lang.NullPointerException:
com.alexdisler.inapppurchases.IabHelper.queryPurchases (IabHelper.java:849)
com.alexdisler.inapppurchases.IabHelper.queryInventory (IabHelper.java:571)
com.alexdisler.inapppurchases.IabHelper.queryInventory (IabHelper.java:535)
com.alexdisler.inapppurchases.IabHelper$2.run (IabHelper.java:630)
java.lang.Thread.run (Thread.java:841)

**Comment by Kaso78** [comment]
Same issue:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
	at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:571)
	at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
	at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
	at java.lang.Thread.run(Thread.java:818)

**Comment by pY4x3g** [comment]
same error from firebase report:


Exception java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
com.alexdisler.inapppurchases.IabHelper.queryPurchases (IabHelper.java:858)
com.alexdisler.inapppurchases.IabHelper.queryInventory (IabHelper.java:557)
com.alexdisler.inapppurchases.IabHelper.queryInventory (IabHelper.java:535)
com.alexdisler.inapppurchases.IabHelper$2.run (IabHelper.java:630)
java.lang.Thread.run (Thread.java:782)
  

Device: mate 9 with android 8

**Comment by AbuHani** [comment]
Same error 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:858)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
       at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
       at java.lang.Thread.run(Thread.java:818)
```
Is anyone working on ?

**Comment by AbuHani** [comment]
here's same issue answered on [stackoverflow](https://stackoverflow.com/questions/15456434/billing-api-v3-iabhelper-nullpointerexception)

Has anyone tried patch fix ?

**Comment by pablo-albaladejo** [comment]
You can try my fork fixing the isuse:

https://github.com/karma-emprendedor/cordova-plugin-inapppurchase

Just add it at the package.json:

`"cordova-plugin-inapppurchase": "git+https://github.com/karma-emprendedor/cordova-plugin-inapppurchase.git",`

**Comment by AbuHani** [comment]
Thanks @pablo-albaladejo 

i'll try and let you know whether that fix the issue or not

**Comment by Reactor13** [comment]
The same issue with lates version of plugin

**Comment by moshi100** [comment]
I solved the issue by adding the following code to labHelper.java file on line 586
```
catch (NullPointerException e) {
  throw new IabException(IABHELPER_UNKNOWN_ERROR, "NPE while refreshing inventory.", e);
}
```
[https://prnt.sc/s2x4a7](https://prnt.sc/s2x4a7)
