### ISSUE TITLE
GoogleSignatureVerifier: com.google.android.gms signature not valid

### ISSUE THREAD

**Issue by dennismarksbury** [AlexDisler/cordova-plugin-inapppurchase#139]
I am able to get through the purchase process the first time.  A fatal error occurs just after the purchase completes (and I think when the consume occurs) that causes the app to crash.  When I attempt to re-open the app, it crashes again during initialization of InAppPurchase.  If I do NOT call getProducts(), then the app loads correctly.

I used logcat to attempt to capture the error (still new to all this).  As best I can tell, it seems to be failing when attempting to generate a public key?  Any help would be appreciated.

For the record, I have attempted this, with the same result, on 3 different devices. 

### Error
AndroidRuntime: Caused by: java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
AndroidRuntime: 	at com.alexdisler.inapppurchases.Security.generatePublicKey(Security.java:85)
AndroidRuntime: 	at com.alexdisler.inapppurchases.Security.verifyPurchase(Security.java:65)
AndroidRuntime: 	at com.alexdisler.inapppurchases.IabHelper.handleActivityResult(IabHelper.java:491)
AndroidRuntime: 	at com.alexdisler.inapppurchases.InAppBillingV3.onActivityResult(InAppBillingV3.java:392)
AndroidRuntime: 	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
AndroidRuntime: 	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:358)
AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7137)
AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)

Consumable
Cordova v 7.0.0
Android 6.0.1

**Comment by dennismarksbury** [comment]
I don't know what happened, but apparently the Google Play Public Key did not copy/paste correctly.  Somewhere in the middle of the string, there were 2 or 3 characters different.  The beginning and ending characters were correct.  But when I copied/pasted it again from Play, it began working.

Sorry.
