### ISSUE TITLE
Crash app after first purchase in Android

### ISSUE THREAD

**Issue by damarni** [AlexDisler/cordova-plugin-inapppurchase#141]
When we do this after we've done an inapp purchase:

`inAppPurchase
            .getProducts(ids)
            .then(function (products) {
            alert('THIS ALERT IS NEVER EXECUTED');
            $scope.$apply(function() {
            $scope.appsPricesLoaded = true;
            for(var i = 0; i < products.length; i++){
                $scope.appsPrice[ products[i].productId ] = products[i].price;
        }
    });
})`

It shows this error:

05-17 00:31:46.509 618-618/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
05-17 00:31:46.687 5043-5056/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
05-17 00:31:46.781 580-963/? E/FastThread: did not receive expected priority boost
05-17 00:31:46.924 22853-22934/com.xaviermartinez.abracadapp E/IABUtil/Security: Invalid key specification.
**05-17 00:31:46.926 22853-22934/com.xaviermartinez.abracadapp E/AndroidRuntime: FATAL EXCEPTION: Thread-10
                                                                               Process: com.xaviermartinez.abracadapp, PID: 22853
                                                                               java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c000079:ASN.1 encoding routines:OPENSSL_internal:HEADER_TOO_LONG
                                                                                   at com.alexdisler.inapppurchases.Security.generatePublicKey(Security.java:85)
                                                                                   at com.alexdisler.inapppurchases.Security.verifyPurchase(Security.java:65)
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:885)
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557)
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
                                                                                   at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
                                                                                   at java.lang.Thread.run(Thread.java:761)**
                                                                                Caused by: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c000079:ASN.1 encoding routines:OPENSSL_internal:HEADER_TOO_LONG
                                                                                   at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:295)
                                                                                   at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47)
                                                                                   at java.security.KeyFactory.generatePublic(KeyFactory.java:357)
                                                                                   at com.alexdisler.inapppurchases.Security.generatePublicKey(Security.java:80)
                                                                                   at com.alexdisler.inapppurchases.Security.verifyPurchase(Security.java:65) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:885) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630) 
                                                                                   at java.lang.Thread.run(Thread.java:761) 
                                                                                Caused by: java.lang.RuntimeException: error:0c000079:ASN.1 encoding routines:OPENSSL_internal:HEADER_TOO_LONG
                                                                                   at com.android.org.conscrypt.NativeCrypto.d2i_PUBKEY(Native Method)
                                                                                   at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:293)
                                                                                   at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47) 
                                                                                   at java.security.KeyFactory.generatePublic(KeyFactory.java:357) 
                                                                                   at com.alexdisler.inapppurchases.Security.generatePublicKey(Security.java:80) 
                                                                                   at com.alexdisler.inapppurchases.Security.verifyPurchase(Security.java:65) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:885) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535) 
                                                                                   at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630) 
                                                                                   at java.lang.Thread.run(Thread.java:761) 
05-17 00:31:47.001 1559-4488/? E/ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 4437:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
                                                  java.lang.Throwable
                                                      at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18179)
                                                      at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18779)
                                                      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
                                                      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2905)
                                                      at android.os.Binder.execTransact(Binder.java:565)
05-17 00:31:47.009 1559-16395/? E/ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 4437:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
                                                   java.lang.Throwable
                                                       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18179)
                                                       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18779)
                                                       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
                                                       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2905)
                                                       at android.os.Binder.execTransact(Binder.java:565)

Please we need to solve it as fast as possible. On iOS is working great.
Thanks in advance!

**Comment by damarni** [comment]
It was that the Android Key on the manifest was not set up correctly. Is working great now :)
