### ISSUE TITLE
java.lang.NullPointerException in IabHelper.queryPurchases(IabHelper.java:849)

### ISSUE THREAD

**Issue by RainerAppel** [AlexDisler/cordova-plugin-inapppurchase#159]
### Your code / steps to reproduce

Got this crash report in Google Play Console. I think this happens when I call inAppPurchase.restorePurchases() in OnDeviceReady.

### Console output
Call Stack report#1:
java.lang.NullPointerException: 
  at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
  at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:571)
  at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
  at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
  at java.lang.Thread.run(Thread.java:818)

Call Stack report#2:
java.lang.NullPointerException: 
  at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
  at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:571)
  at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
  at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
  at java.lang.Thread.run(Thread.java:761)

### Type of product you are working with consumable/non-consumable/subscription
 consumable/non-consumable

### Version of cordova
7.0.1

### Version of iOS/Android
report #1: Samsung Galaxy A5(2017) (a5y17lte), 3072MB RAM, Android 6.0
report #2: LGE Nexus 5X (bullhead), 2048MB RAM, Android 7.1

**Comment by nilebma** [comment]
Seems to be the same issue as reported here : 
https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/168

**Comment by RainerAppel** [comment]
Duplicate of #168.
