### ISSUE TITLE
Cannot read property 'code' of null

### ISSUE THREAD

**Issue by Screeze** [AlexDisler/cordova-plugin-inapppurchase#197]
Hi, my Sentry Error reporting is reporting following error a few times on my new app, which is being thrown by this plugin:

Cordova Platforms  : android 6.4.0
Using     "cordova-plugin-inapppurchase": "^1.2.0"

Reported on following device for example:
browser Chrome Mobile 33.0.0
browser.name Chrome Mobile
device GT-I9060I
device.family Samsung GT-I9060I
environment android
level error
osAndroid 4.4.4

```
Error: Uncaught (in promise): TypeError: Cannot read property 'code' of null
TypeError: Cannot read property 'code' of null
    at file:///android_asset/www/plugins/cordova-plugin-inapppurchase/www/index-android.js:102:24
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:52)
    at processMessage (file:///android_asset/www/cordova.js:1114:17)
    at processMessages (file:///android_asset/www/cordova.js:1137:9)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)
    at Object.t._inner.t._inner.fork.onInvoke (file:///android_asset/www/build/vendor.js:1:67220)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14916)
    at r.run (file:///android_asset/www/build/polyfills.js:3:10143)
    at file:///android_asset/www/build/polyfills.js:3:20242
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)
    at Object.t._inner.t._inner.fork.onInvokeTask (file:///android_asset/www/build/vendor.js:1:67134)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15581)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)
    at o (file:///android_asset/www/build/polyfills.js:3:7894)
```
Any idea what it is?

**Comment by garretfick** [comment]
I'm seeing this issue too. Were you able to find a solution?
