### ISSUE TITLE
Android crashes in IabHelper.java

### ISSUE THREAD

**Issue by kristfal** [AlexDisler/cordova-plugin-inapppurchase#52]
Hey,

we're seeing a few crashes in production. Native stack:

```
#0. Crashed: Thread-5698: 0 0 0x0000000000000000
       at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:571)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
       at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:571)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
       at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
       at java.lang.Thread.run(Thread.java:818)

#0. Crashed: Thread-5698: 0 0 0x0000000000000000
       at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:571)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
       at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
       at java.lang.Thread.run(Thread.java:818)
```

Offending code:

```java
int queryPurchases(Inventory inv, String itemType) throws JSONException, RemoteException {
        // Query purchases
        logDebug("Querying owned items, item type: " + itemType);
        logDebug("Package name: " + mContext.getPackageName()); // Line 849
        boolean verificationFailed = false;
        // Only allow purchase verification to be skipped if we are debuggable
        boolean skipPurchaseVerification = (this.mSkipPurchaseVerification  &&
                    ((mContext.getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0));
        String continueToken = null;

        do {
     
```

Plugin version: cordova-plugin-inapppurchase 0.5.0 "In App Purchase"
Cordova version: 6.1.0
Cordova Android version: 5.1.1

Any idea how to resolve this?

**Comment by mirstan** [comment]
+1 

Same issue on Android 4.4:

`java.lang.NullPointerException
	at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:858)
	at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557)
	at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
	at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
	at java.lang.Thread.run(Thread.java:841)`

**Comment by derrickroccka** [comment]
+1... Any progress on this???

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:858)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:557)
       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
       at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
       at java.lang.Thread.run(Thread.java:818)`

Thanks!

**Comment by guyman** [comment]
+1 This issue crashes my app in production without any workaround.

**Comment by Senglejan** [comment]
Hello! 

This looks related to the signing of the apk. Recently android changed the structure of an android app and thus the release-signing.properties file should placed in 

platforms/android/app/ 

If you notice there are 2 build.gradle files, one in android platform root and the other in android/app/ . If you check the build.gradle located in android/app it contains the reference to the release-signing.proeperties files so thats where we have to put the file now.

I pushed new release apk with the following files also in platforms/android/app/ directory 👍 

release-signing.properties
release.keystore
google-services.json

**Comment by Zakrevskijj** [comment]
+1 same here
