### ISSUE TITLE
Testing on Emulator

### ISSUE THREAD

**Issue by vcrepin** [AlexDisler/cordova-plugin-inapppurchase#68]
Please include:

### Your code / steps to reproduce
```js

function restorePurchase () {
      vm.isFetching = true;
      if($window.cordova) {
        inAppPurchase
          .restorePurchases().then(
            function (data) {
              vm.isFetching = false;
              $log.info(angular.toJson(data));
              var product;
              for (var j = 0, len = data.length; j < len; j++) {
                product = data[j];
                if (product.productId = "com.elapsetech.mobile.golfmatchplay.pro") {
                  ToastService.showInfo("Enjoy the Ads free version! Transaction: "+product.transactionId, 2000);
                  $localStorage.hasProVersion = data;
                  admobSvc.removeBanner();
                  return;
                }
              }
              ToastService.showWarning("Could not find a previously bought Ads free version", 3000);
            }
          ).catch(
            function (err) {
              vm.isFetching = false;
              $log.error(angular.toJson(err));
              ToastService.showError("An error occurred while restoring the Ads free version", 3000);
            }
          );
      } else {
        vm.isFetching = false;
        ToastService.showWarning("In app purchase not available on this platform", 3000);
      }
    }
```
### Console output

E/PluginManager: Uncaught exception from plugin
                 java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
                     at com.alexdisler.inapppurchases.IabHelper.startSetup(IabHelper.java:276)
                     at com.alexdisler.inapppurchases.InAppBillingV3.init(InAppBillingV3.java:184)
                     at com.alexdisler.inapppurchases.InAppBillingV3.execute(InAppBillingV3.java:162)
                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                     at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
                     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
                     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:148)
                     at android.os.HandlerThread.run(HandlerThread.java:61)

### Type of product you are working with consumable/non-consumable/subscription
 non-consumable
### Version of cordova

6.3.1

**Comment by skotturi** [comment]
I think you have to use a device. 

According to: https://developer.android.com/google/play/billing/billing_testing.html#billing-testing-static

Install your application on an Android-powered device.
You cannot use the emulator to test In-app Billing; you must install your application on a device to test In-app Billing.
To learn how to install an application on a device, see Running on a device.
